build:
  version: "3.0"

loans:
  message: "Welcome to EazyBank loans related local APIs"
  contactDetails:
    name: "Carlos Henrique - Developer"
    email: "carlos@gmail.com"
  onCallSupport:
    - +55 (21) 99035-1234
    - +55 (21) 92325-1564